### PR TITLE
Fix the issue https://github.com/TransitApp/SVProgressHUD/issues/481.

### PR DESCRIPTION
**Pull request by bhapca**
A potential approach for fixing the issue.

### CODE REVIEW

**Comment by Dids** [comment]
Did this remove the background circle drawing/graphic?

Here's a screenshot that shows what I mean:
screen shot 2015-09-20 at 13 51 45

**Comment by bhapca** [comment]
I'm not sure. In what context are you seeing this ? What methods are you calling. Can you reproduce it with the Demo app ? 

By the look of it, is seems that you're calling some variant of showProgress: ? 

If I run it on the Demo app, in the commit preceding my change, the appearance looks similar: 
ios simulator screen shot 21 sep 2015 10 54 01


What would your expected behaviour be ?

**Comment by Dids** [comment]
As I recall, there was a very faint grey circle behind the actual progress circle, which is what is missing here. Or am I imagining things? :P

**Comment by honkmaster** [comment]
... I can not remember a "faint grey circle".

**Comment by Dids** [comment]
Found a screenshot by googling. Here's more or less how it looked like for me before:

**Comment by honkmaster** [comment]
Oh I see now. Will investigate this.

**Comment by honkmaster** [comment]
The "issue" is not related to this bugfix. Will go deeper into history.

**Comment by honkmaster** [comment]
Should be fixed. Man this bug was introduced at least 2 years ago and no one ever noticed it. was a stupid copy & paste error.

**Comment by Dids** [comment]
:+1:

**Pull request merged**
