### PR TITLE
Fix image paths to support frameworks (and Swift) introduced in Cocoapods 0.36 beta

### LINKED ISSUE #396: Assets don't show up when installing with cocoapods 0.36.0.beta.1 (modules)
Images don't show after installing SVProgressHUD 1.1.2 (or `:head`) via cocoapods 0.36.0.beta.1.

image

Code that shows the HUD:

```
SVProgressHUD.showSuccessWithStatus("XXXX canceled")
```

Podfile:
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'SVProgressHUD', '1.1.2'
```

Cocoapods version:
```
$ pod --version
0.36.0.beta.1
```

No warnings are shown during compilation.

### PR DESCRIPTION
**Pull request by tmu**
This fixes #396 for Cocoapods 0.36 beta. I didn't yet have time to test this on a static library setup, but it works nicely in my Swift application. 

There's some whitespace cleanup automatically done by the editor.

### CODE REVIEW

**Comment by ldiqual** [comment]
Confirmed that it works in the original issue. My only concern is that your diff is polluted by whitespace changes, but it doesn't really matter.

**Comment by honkmaster** [comment]
Regarding whitespaces: This is a valid concern. Could you please remove them?

**Comment by tmu** [comment]
You mean add back leading whitespace to empty lines in SVProgressHUD/SVIndefiniteAnimatedView.m? 

Sure, if you want.

**Comment by ldiqual** [comment]
:+1:

**Comment by tmu** [comment]
Brought back the leading whitespace on empty lines

**Comment by ldiqual** [comment]
Looks good to me. @honkmaster Can you merge and update the podspec?
The only alternative I have right now is to copy the assets into my main project, which is not ideal :/

**Comment by honkmaster** [comment]
BTW: This fix only works in iOS 8 and above => crashes on iOS 7, will revert back to old version.

**Comment by honkmaster** [comment]
Should be fixed by #406.

**Pull request merged**
