### PR TITLE
Allows the minimum value for displayDurationForString to be configured (if needed)

### PR DESCRIPTION
**Pull request by MichaelLyst**
Adding the ability to set the length of time that is takes to dismiss the HUD when needed.

### CODE REVIEW

**Comment by honkmaster** [comment]
The minimum is should be zero, so by default it should have no effect, only if the user has set the value it should.

**Comment by MichaelLyst** [comment]
Anytime there is a string to show, it goes to 5 seconds. For example. With a string like "Your product has been added to a collection for later viewing" and the current logic 

MIN((float)string.length*0.06 + 0.5, 5.0);
MIN(62 * 0.6 + 0.5, 5.0)
MIN(37.7, 5.0)
5.0

If we want to change the value 5.0, we need a way to set that. That is what this PR offers. 

self.minimumDismissTimeInterval = 0.5
MIN((float)string.length * 0.06 + 0.5, self.minimumDismissTimeInterval);
MIN(62 * 0.6 + 0.5, 2.0)
MIN(37.7, 2.0)
2.0

**Comment by honkmaster** [comment]
Ok, sorry my fault. was reading this from my mobile and hadn`t the code in front of me. Will merge now.

**Comment by NearMilk** [comment]
Why change 0.06 to 0.6 ?

**Pull request merged**
